### PR TITLE
fix: dependencies and bcrypt for hashing password

### LINKED ISSUE #440: [Bug]: dependencies
### Describe the Bug

consider removing webpack and or webpack-dev-server as create-react-app's `react-scripts` already includes webpack.

consider removing md5 in favor of using bcrypt or argon2 for hashing

### Steps to Reproduce

n/a

### Screenshots

_No response_

### Which device are you using?

PC

### Which operating system are you using?

Derbian 12

### Which browser are you using?

Firefox

### Additional Context

_No response_

### Contribute

- [ ] I am willing to contribute and submit a pull request

### PR DESCRIPTION
**Pull request by NandishDPatel**
added bcrypt for hashing inplace of md5 and removed webpack-dev and webpack dependecies from package.json
working-photo

fixes issue #440

### CODE REVIEW

File: server/database.js [hunk 1]
```diff
@@ -1,95 +1,97 @@
...
     if (err) {
         // Cannot open db
         console.error(err.message);
         throw err;
     } else {
         console.log("Connected to Sqlite DB.");
 
-        db.run(
-            `CREATE TABLE IF NOT EXISTS User (
+        try {
```
Comment (NandishDPatel) [inline server/database.js:14]: Made the async function as bcrypt returns a promise

File: server/routes/users/loginUser.js [hunk 2]
```diff
@@ -42,11 +42,12 @@ router.post("/api/login", (req, res, next) => {
         const existingUser = users.find(
             (user) =>
                 user.username === data.username &&
-                user.email === data.email &&
-                user.password === data.password
+                user.email === data.email
         );
 
-        if (existingUser) {
+        const isMatch = await bcrypt.compare(data.password, existingUser.password);
```
Comment (NandishDPatel) [inline server/routes/users/loginUser.js:48]: can't compare pwd using === in bcrypt so defined the password logic seperately

**Review by NandishDPatel — COMMENTED** [review]
made some comments about for better understanding

File: server/database.js (hunk 1 above)
Comment (gbowne1) [reply server/database.js:14]: Good idea.

File: server/routes/users/loginUser.js (hunk 2 above)
Comment (gbowne1) [reply server/routes/users/loginUser.js:48]: yes, we should not use md5 anymore.

I couldn't find a way to demonstrate t working properly because successful login isn't logged

**Review by gbowne1 — APPROVED** [review]
Checked out this change locally for testing and review for merge.

This change replaces md5 with bcrypt and also removes webpack which we aren't using here anymore anyway. CRA also has it's own bundlers anyway 

This appears to be working correctly and implemented fixes for that 

Approving this PR for merge 

@NandishDPatel  Thanks for the opportunity to review your PR and for your contribution to this project 

Please feel free to work on the issues in this project or any others in my GitHub  https://github.com/gbowne1
